[package]
name = "sp1-runner"
description = "Runner utility for validating Arbitrum blocks in SP1"
version = "0.1.0"
edition = "2024"

[dependencies]
sp1-core-executor = { workspace = true }
sp1-sdk = { workspace = true }
prover = { workspace = true }

bincode = { workspace = true }
clap = { workspace = true }
rkyv = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
