
[package]
name = "vid-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4"
ark-serialize = { version = "0.4", features = ["derive"] }
base64 = "0.22"
derive_more = "0.99.17"
base64-bytes = "0.1"
serde_json = "1.0"
tagged-base64 = { git = "https://github.com/EspressoSystems/tagged-base64", tag = "0.3.4" }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10.1" }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2", features = [
    "test-srs", "std"
], default-features = false}
jf-utils = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2", features = [
], default-features = false}
trait-set = "0.3.0"
num-traits = "0.2.17"
derivative = "2.2"
