[package]
name = "stylus"
version = "0.1.0"
edition = "2021"

[dependencies]
arbutil = { path = "../arbutil/" }
prover = { path = "../prover/", default-features = false, features = ["native"] }
wasmer = { path = "../tools/wasmer/lib/api" }
wasmer-vm = { path = "../tools/wasmer/lib/vm/" }
wasmer-types = { path = "../tools/wasmer/lib/types/" }
wasmer-compiler-singlepass = { path = "../tools/wasmer/lib/compiler-singlepass", default-features = false, features = ["std", "unwind", "avx"] }
wasmer-compiler-cranelift = { path = "../tools/wasmer/lib/compiler-cranelift" }
wasmer-compiler-llvm = { path = "../tools/wasmer/lib/compiler-llvm", optional = true }
user-host-trait = { path = "../wasm-libraries/user-host-trait/" }
derivative = "2.2.0"
parking_lot = "0.12.1"
thiserror = "1.0.33"
bincode = "1.3.3"
libc = "0.2.108"
eyre = "0.6.5"
rand = "0.8.5"
fnv = "1.0.7"
sha3 = "0.10.5"
hex = "0.4.3"

[dev-dependencies]
num-bigint = "0.4.4"

[features]
default = ["rayon", "singlepass_rayon"]
llvm = ["dep:wasmer-compiler-llvm"]
benchmark = []
timings = []
singlepass_rayon = ["prover/singlepass_rayon", "wasmer-compiler-singlepass/rayon"]
rayon = ["prover/rayon"]

[lib]
crate-type = ["lib", "staticlib"]
