language = "C"
include_guard = "arbitrator_bindings"

[parse]
parse_deps = true
include = ["arbutil", "prover"]
extra_bindings = ["arbutil", "prover"]

[enum]
prefix_with_name = true

[export]
include = ["EvmApiMethod"]
