[workspace]
members = [
    "arbutil",
    "bench",
    "brotli",
    "caller-env",
    "jit",
    "prover",
    "stylus",
]
exclude = [
    "langs",
    "stylus/tests",
    "tools",
    "wasm-libraries",
    "wasm-testsuite",
]
resolver = "2"

[workspace.package]
authors = ["Offchain Labs"]
edition = "2021"
homepage = "https://arbitrum.io"
license = "BSL"
publish = false
repository = "https://github.com/OffchainLabs/nitro.git"
rust-version = "1.88"

[workspace.dependencies]
lazy_static = "1.4.0"
num_enum = { version = "0.7.2", default-features = false }
ruint2 = "1.9.0"
wasmparser = "0.121"

[profile.release]
debug = true
