[workspace]
members = [
    "arbutil",
    "bench",
    "brotli",
    "caller-env",
    "jit",
    "prover",
    "stylus",
]
exclude = [
    "langs",
    "stylus/tests",
    "tools",
    "wasm-libraries",
    "wasm-testsuite",
]
resolver = "2"

[workspace.package]
authors = ["Offchain Labs"]
edition = "2021"
homepage = "https://arbitrum.io"
license = "BSL"
publish = false
repository = "https://github.com/OffchainLabs/nitro.git"
rust-version = "1.88"

[workspace.dependencies]
clap = { version = "4.4.8" }
digest = { version = "0.10.7" }
eyre = { version = "0.6.5" }
fnv = { version = "1.0.7" }
gperftools = { version = "0.2.0" }
hex = { version = "0.4.3" }
lazy_static = { version = "1.4.0" }
num_enum = { version = "0.7.2", default-features = false }
num-traits = { version = "0.2.17" }
ruint2 = { version = "1.9.0" }
serde = { version = "1.0.130" }
siphasher = { version = "0.3.10" }
tiny-keccak = { version = "2.0.2" }
wasmparser = { version = "0.121" }

prover = { path = "prover" }
wasmer = { path = "tools/wasmer/lib/api" }

[profile.release]
debug = true
