[package]
name = "jit"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arbutil = { workspace = true }
brotli = { workspace = true, features = ["wasmer_traits"] }
caller-env = { workspace = true, features = ["wasmer_traits"] }
eyre = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
prover = { workspace = true, features = ["native"] }
rand = { workspace = true }
rand_pcg = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
structopt = { workspace = true }
stylus = { workspace = true }
thiserror = { workspace = true }
wasmer = { workspace = true }
wasmer-compiler-cranelift = { workspace = true }
wasmer-compiler-llvm = { workspace = true, optional = true }

[features]
llvm = ["dep:wasmer-compiler-llvm"]
