[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[dependencies]
arbutil = { path = "../arbutil/" }
prover = { path = "../prover/", default-features = false, features = ["native"] }
stylus = { path = "../stylus/", default-features = false }
wasmer = { path = "../tools/wasmer/lib/api/" }
wasmer-compiler-llvm = { path = "../tools/wasmer/lib/compiler-llvm/", optional = true }
wasmer-compiler-cranelift = { path = "../tools/wasmer/lib/compiler-cranelift/" }
eyre = "0.6.5"
parking_lot = "0.12.1"
rand = { version = "0.8.4", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false }
thiserror = "1.0.33"
hex = "0.4.3"
structopt = "0.3.26"
sha3 = "0.9.1"
libc = "0.2.132"
ouroboros = "0.15.5"

[features]
llvm = ["dep:wasmer-compiler-llvm"]
