version: '3.9'
services:
  orchestrator:
    image: ghcr.io/espressosystems/espresso-sequencer/orchestrator:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_ORCHESTRATOR_PORT:$ESPRESSO_ORCHESTRATOR_PORT"
    environment:
      - ESPRESSO_ORCHESTRATOR_PORT
      - ESPRESSO_ORCHESTRATOR_NUM_NODES=2
      - ESPRESSO_ORCHESTRATOR_START_DELAY=5s
      - ESPRESSO_ORCHESTRATOR_NEXT_VIEW_TIMEOUT=30s
      - ESPRESSO_ORCHESTRATOR_MIN_TRANSACTIONS=1
      - ESPRESSO_ORCHESTRATOR_MIN_PROPOSE_TIME=0s
      - ESPRESSO_ORCHESTRATOR_MAX_PROPOSE_TIME=1s
      - RUST_LOG
      - RUST_LOG_FORMAT

  da-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_DA_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy

  consensus-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_CONSENSUS_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy

  espresso-sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment) and the optional submission API
    command: sequencer -- http -- query -- submit -- status
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - ESPRESSO_STATE_RELAY_SERVER_URL
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_0
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://espresso-sequencer1:$ESPRESSO_SEQUENCER_API_PORT
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      consensus-server:
        condition: service_healthy
      da-server:
        condition: service_healthy
      state-relay-server:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  espresso-sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_SEQUENCER1_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - ESPRESSO_STATE_RELAY_SERVER_URL
      - RUST_LOG
      - RUST_LOG_FORMAT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://espresso-sequencer0:$ESPRESSO_SEQUENCER_API_PORT
    depends_on:
      orchestrator:
        condition: service_healthy
      consensus-server:
        condition: service_healthy
      da-server:
        condition: service_healthy
      state-relay-server:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  commitment-task:
    image: ghcr.io/espressosystems/espresso-sequencer/commitment-task:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_COMMITMENT_TASK_PORT:$ESPRESSO_COMMITMENT_TASK_PORT"
    command: commitment-task --deploy
    environment:
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC=$ESPRESSO_COMMITMENT_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_HOTSHOT_ACCOUNT_INDEX
      - ESPRESSO_COMMITMENT_TASK_PORT
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      espresso-sequencer0:
        condition: service_healthy
      consensus-server:
        condition: service_healthy
      da-server:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  state-relay-server:
    image: ghcr.io/espressosystems/espresso-sequencer/state-relay-server:arbitrum-integrationmusl
    ports:
      - "$ESPRESSO_STATE_RELAY_SERVER_PORT:$ESPRESSO_STATE_RELAY_SERVER_PORT"
    environment:
      - ESPRESSO_STATE_RELAY_SERVER_PORT
      - ESPRESSO_STATE_SIGNATURE_WEIGHT_THRESHOLD
      - RUST_LOG
      - RUST_LOG_FORMAT
