version: "3.9"
services:
  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:latest
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
      - "$ESPRESSO_BUILDER_PORT:$ESPRESSO_BUILDER_PORT"
      - "$ESPRESSO_DEV_NODE_PORT:$ESPRESSO_DEV_NODE_PORT"
    environment:
      - ESPRESSO_BUILDER_PORT
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX
      - ESPRESSO_DEV_NODE_PORT
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - RUST_LOG=info
      - RUST_LOG_FORMAT
    extra_hosts:
      - "host.docker.internal:host-gateway"
