[package]
name = "wasm-testsuite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbutil = { path = "../arbutil" }
prover = { path = "../prover" }
structopt = "0.3.23"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.67"
eyre = "0.6.5"
hex = "0.4.3"

[workspace]
members = []
