[package]
name = "callerenv"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_pcg = { version = "0.3.1", default-features = false }
rand = { version = "0.8.4", default-features = false }

[features]
static_caller = []
