[package]
name = "sp1-builder"
description = "A builder crate that builds SP1 programs, necessary metadata, then run bootloader to generated bootloaded SP1 program"
version = "0.1.0"
edition = "2024"

[dependencies]
sp1-core-executor = { workspace = true }
sp1-sdk = { workspace = true }

clap = { workspace = true }
serde_json = { workspace = true }
wasmer = { workspace = true, features = ["llvm"] }
wasmparser = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
