[package]
name = "go-stub"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
fnv = "1.0.7"
rand = { version = "0.8.4", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false }
arbutil = { path = "../../arbutil/", features = ["wavm"] }
go-abi = { path = "../go-abi" }

[features]
