[package]
name = "wasi-stub"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
paste = {versoion="1.0.14"}
callerenv = { path = "../../callerenv/", features = ["static_caller"] }
rand = { version = "0.8.4", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false }
