[package]
name = "wasi-stub"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
paste = { version = "1.0.14" }
caller-env = { path = "../../caller-env/", features = ["static_caller"] }
wee_alloc = "0.4.2"
