name: "Arbitrator skip CI"

on:
  pull_request:
    paths-ignore:
      - 'arbitrator/**'
      - 'contracts/src/osp/**'
      - 'contracts/src/mock/**'
      - 'contracts/test/**'
      - 'contracts/hardhat.config.ts'
      - 'Makefile'

jobs:
  coverage:
    name: Run Arbitrator tests
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "doing nothing"
