name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  # formatting:
  #   name: Formatting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Go mod tidy checker
  #      id: gomodtidy
  #      uses: ./.github/actions/gomodtidy

  build:
    name: Build and Test Bold
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup node/yarn
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'
          cache-dependency-path: "**/yarn.lock"

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false

      - name: AbiGen (nitro)
        run: make contracts

      - name: Get dependencies
        working-directory: ./bold
        run: |
          go get -v -t -d ./...

      - name: Build
        working-directory: ./bold
        run: go build -v ./...

      - name: Test
        working-directory: ./bold      
        run: ANVIL=$(which anvil) go test -v -covermode=atomic -coverprofile=coverage.out -timeout=20m ./...

      #- name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v4
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

