name: Go

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  # formatting:
  #   name: Formatting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5

  #     - name: Go mod tidy checker
  #      id: gomodtidy
  #      uses: ./.github/actions/gomodtidy

  build:
    name: Build and Test Bold
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup node/yarn
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'yarn'
          cache-dependency-path: "**/yarn.lock"

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false
          version: v1.0.0

      - name: AbiGen (nitro)
        run: make contracts

      - name: Get dependencies
        working-directory: ./bold
        run: |
          go get -v -t ./...

      - name: Build
        working-directory: ./bold
        run: go build -v ./...

      - name: Test
        working-directory: ./bold      
        run: ANVIL=$(which anvil) go test -v -covermode=atomic -coverprofile=coverage.out -timeout=30m ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

