name: Release CI
run-name: Release CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  build_and_run:
    runs-on: ubuntu-8

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Check PR Label For Release label
      if: ${{ !contains(github.event.*.labels.*.name, 'release') }}
      run: |
        echo "Not a release candidate. Skipping workflow."
        exit 0

    - name: Build nitro-fuzzer Docker Image
      run: docker build --target nitro-fuzzer -t nitro-fuzzer .

    - name: Run Docker Container
      run: docker run nitro-fuzzer
